[versions]
minecraft = "1.20.4"
fabric-loom = "1.4-SNAPSHOT"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
